
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<form action="agregarCliente" method="post">

    <label for="nombre">Nombre:</label>
    <input type="text" class="form-control" id="nombre" name="nombre" required>

    <label class="form-label" for="apellido">Apellido:</label>
    <input type="text" class="form-control" id="apellido" name="apellido" required>


    <label for="correoElectronico">Correo Electronico:</label>
    <input type="email" class="form-control" id="correoElectronico" name="correoElectronico" required>

    <label class="form-label" for="descripcion">Fecha de nacimiento:</label>
    <input type="date" class="form-control"  name="descripcion" required></textarea>

    <label for="dni">Documento:</label>
    <input type="text" class="form-control" id="DNI" name="DNI" step="0.01" required>

    <label for="direccion">Direccion:</label>
    <input type="text" class="form-control" id="Direccion" name="Direccion" step="0.01" required>

    <button class="btn btn-success" type="submit">Agregar Cliente</button>
</form>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>