
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<?php if (isset($_SESSION['id_usuario'])) { ?>
  <div class="d-grid gap-2 col-6 mx-auto">
    <a href="<?php echo BASE_URL . 'formAgregarCliente/'; ?>" class="btn btn-success btn-sm">Agregar Cliente</a>

  </div>
<?php } ?>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre del Cliente</th>
      <th>Ver Detalle</th>
      <?php if (isset($_SESSION['id_usuario'])) { ?>
        <th>Opciones</th>
      <?php } ?>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($clientes as $index) { ?>
      <tr>
        <td><?php echo $index->Nombre; ?></td>
        <td><a href="<?php echo BASE_URL . 'ClienteDetalles/' . $index->ID_Cliente; ?>" class="btn btn-primary btn-sm">Ver Detalle</a></td>

        <?php if (isset($_SESSION['id_usuario'])) { ?>
          <td>
            <a href="<?php echo BASE_URL . 'actualizarCliente/' . $index->ID_Cliente; ?>" class="btn btn-warning">Editar</a>
            <a href="<?php echo BASE_URL . 'eliminarCliente/' . $index->ID_Cliente; ?>" class="btn btn-danger">Eliminar</a>
          </td>
        <?php } ?>

      </tr>
    <?php } ?>
  </tbody>
</table>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
