<h2>Cliente</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID Cliente</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>CorreoElectronico</th>
            <th>FechaNacimiento</th>
            <th>DNI</th>
            <th>Direccion</th>
            <?php if (isset($_SESSION['id_usuario'])) { ?>
                <th>Opciones</th>
            <?php } ?>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?php echo $cliente->ID_Cliente; ?></td>
            <td><?php echo $cliente->Nombre; ?></td>
            <td><?php echo $cliente->Apellido; ?></td>
            <td><?php echo $cliente->CorreoElectronico; ?></td>
            <td><?php echo $cliente->FechaNacimiento; ?></td>
            <td><?php echo $cliente->DNI; ?></td>
            <td><?php echo $cliente->Direccion; ?></td>
            <?php if (isset($_SESSION['id_usuario'])) { ?>
                <td>
                    <a href="<?php echo BASE_URL . 'formActualizarCliente/' . $cliente->ID_Cliente; ?>" class="btn btn-warning">Editar</a>
                    <a href="<?php echo BASE_URL . 'eliminarCliente/' . $cliente->ID_Cliente; ?>" class="btn btn-danger">Eliminar</a>
                </td>
            <?php } ?>
        </tr>
    </tbody>
</table>
<?php require_once 'templates/ClienteDetallesViajes.phtml'; ?>