<?php if (isset($_SESSION['id_usuario'])) { ?>
  <div class="d-grid gap-2 col-6 mx-auto">
    <a href="<?php echo BASE_URL . 'formAgregarCliente/'; ?>" class="btn btn-success btn-sm">Agregar Cliente</a>

  </div>
<?php } ?>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre del Cliente</th>
      <th>Ver Detalle</th>
      <?php if (isset($_SESSION['id_usuario'])) { ?>
        <th>Opciones</th>
      <?php } ?>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($clientes as $index) { ?>
      <tr>
        <td><?php echo $index->Nombre; ?></td>
        <td><a href="<?php echo BASE_URL . 'clienteDetalles/' . $index->ID_Cliente; ?>" class="btn btn-primary btn-sm">Ver Detalle</a></td>

        <?php if (isset($_SESSION['id_usuario'])) { ?>
          <td>
            <a href="<?php echo BASE_URL . 'formActualizarCliente/' . $index->ID_Cliente; ?>" class="btn btn-warning">Editar</a>
            <a href="<?php echo BASE_URL . 'eliminarCliente/' . $index->ID_Cliente; ?>" class="btn btn-danger">Eliminar</a>
          </td>
        <?php } ?>

      </tr>
    <?php } ?>
  </tbody>
</table>