<?php require_once 'templates/Header.phtml'; ?>

<h2>Cliente</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID Cliente</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>CorreoElectronico</th>
            <th>FechaNacimiento</th>
            <th>DNI</th>
            <th>Direccion</th>
            <?php if ($isAdmin) { ?>
                <th>Opciones</th>
            <?php } ?>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?php echo $cliente->id_cliente; ?></td>
            <td><?php echo $cliente->nombre; ?></td>
            <td><?php echo $cliente->apellido; ?></td>
            <td><?php echo $cliente->correo_electronico; ?></td>
            <td><?php echo $cliente->fecha_nacimiento; ?></td>
            <td><?php echo $cliente->dni; ?></td>
            <td><?php echo $cliente->direccion; ?></td>
            <?php if ($isAdmin) { ?>
                <td>
                    <a href="<?php echo BASE_URL . 'FormActualizarCliente/' . $cliente->id_cliente; ?>" class="btn btn-warning">Editar</a>
                    <a href="<?php echo BASE_URL . 'EliminarCliente/' . $cliente->id_cliente; ?>" class="btn btn-danger">Eliminar</a>
                </td>
            <?php } ?>
        </tr>
    </tbody>
</table>

<?php require_once 'templates/ClienteDetallesViajes.phtml'; ?>
<?php require_once 'templates/Footer.phtml'; ?>