<footer>
      <p>Contacto: yael.e.orellano@gmail.com, Corbellini47gmail.com</p>
      <p>No dudes en ponerte en contacto con nosotros para comenzar a planificar tu próxima aventura.
            ¡Esperamos poder ser parte de tus recuerdos de viaje inolvidables!</p>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>

</html>