
<footer>
      <p>Contacto: yael.e.orellano@gmail.com, Corbellini47gmail.com</p>
      <p>No dudes en ponerte en contacto con nosotros para comenzar a planificar tu próxima aventura.
            ¡Esperamos poder ser parte de tus recuerdos de viaje inolvidables!</p>
</footer>
</body>

</html>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>