<?php require_once 'templates/Header.phtml'; ?>

<form action="AgregarViaje" method="post">

    <label for="destino">Destino:</label>
    <input type="text" class="form-control" id="destino" name="destino" required>

    <label class="form-label" for="fechaSalida">Fecha de Salida:</label>
    <input type="date" class="form-control" id="fechaSalida" name="fechaSalida" required>


    <label for="fechaRegreso">Fecha de Llegada:</label>
    <input type="date" class="form-control" id="fechaRegreso" name="fechaRegreso" required>

    <label class="form-label" for="descripcion">Descripción:</label>
    <textarea id="descripcion" name="descripcion" required></textarea>

    <label for="precio">Precio:</label>
    <input type="number" class="form-control" id="precio" name="precio" step="0.01" required>

    <label class="form-label" for="cliente">Cliente:</label>
    <select class="form-control" id="cliente" name="cliente" required>
        <?php foreach ($clientes as $cliente) { ?>
            <option value="<?php echo $cliente->id_cliente; ?>"><?php echo $cliente->nombre; ?></option>
        <?php } ?>
    </select>
    <button class="btn btn-success" type="submit">Agregar Viaje</button>
</form>
<?php require_once 'templates/Footer.phtml'; ?>