
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<form action="actualizarViaje/<?php echo $viaje->ID_Viaje; ?>" method="POST">
    <div>
        <label for="destino">Destino:</label>
        <input type="text" class="form-control" id="destino" name="destino" value="<?php echo $viaje->Destino; ?>" required>
    </div>
    <div>
        <label class="form-label" for="fechaSalida">Fecha de Salida:</label>
        <input type="date" class="form-control" id="fechaSalida" name="fechaSalida" value="<?php echo $viaje->FechaSalida; ?>" required>
    </div>
    <div>
        <label for="fechaRegreso">Fecha de Regreso:</label>
        <input type="date" class="form-control" id="fechaRegreso" name="fechaRegreso" value="<?php echo $viaje->FechaRegreso; ?>" required>
    </div>
    <div>
        <label class="form-label" for="descripcion">Descripción:</label>
        <input type="text" id="descripcion" name="descripcion" value="<?php echo $viaje->Descripcion; ?>" required>
    </div>
    <div>
        <label for="precio">Precio:</label>
        <input type="number" class="form-control" id="precio" name="precio" step="0.01" value="<?php echo $viaje->Precio; ?>" required>
    </div>
    <div>
        <label class="form-label" for="cliente">Cliente:</label>
        <select class="form-control" id="cliente" name="cliente" required>
            <?php foreach ($clientes as $cliente) { ?>
                <option value="<?php echo $cliente->ID_Cliente; ?>" <?= $cliente->ID_Cliente == $viaje->id_Cliente ? ' selected="selected"' : ''; ?>>
                    <?php echo $cliente->Nombre; ?>
                </option>
            <?php } ?>
        </select>

    </div>
    <button class="btn btn-warning" type="submit">Actualizar</button>
</form>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>