

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<form action="agregarViaje" method="post">

    <label for="destino">Destino:</label>
    <input type="text" class="form-control" id="destino" name="destino" required>

    <label class="form-label" for="fechaSalida">Fecha de Salida:</label>
    <input type="date" class="form-control" id="fechaSalida" name="fechaSalida" required>


    <label for="fechaRegreso">Fecha de Llegada:</label>
    <input type="date" class="form-control" id="fechaRegreso" name="fechaRegreso" required>

    <label class="form-label" for="descripcion">Descripción:</label>
    <textarea id="descripcion" name="descripcion" required></textarea>

    <label for="precio">Precio:</label>
    <input type="number" class="form-control" id="precio" name="precio" step="0.01" required>

    <label class="form-label" for="cliente">Cliente:</label>
    <select class="form-control" id="cliente" name="cliente" required>
        <?php foreach ($clientes as $cliente) { ?>
            <option value="<?php echo $cliente->ID_Cliente; ?>"><?php echo $cliente->Nombre; ?></option>
        <?php } ?>
    </select>


    <button class="btn btn-success" type="submit">Agregar Viaje</button>
</form>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>