<form action="actualizarCliente/<?php echo $clientes->ID_Cliente; ?>" method="post">
    <label for="nombre">Nombre:</label>
    <input type="text" class="form-control" id="nombre" name="nombre" value="<?php echo $clientes->Nombre; ?>" required>

    <label class="form-label" for="apellido">Apellido:</label>
    <input type="text" class="form-control" id="apellido" name="apellido" value="<?php echo $clientes->Apellido; ?>" required>


    <label for="correoElectronico">Correo Electronico:</label>
    <input type="email" class="form-control" id="correoElectronico" name="correoElectronico" value="<?php echo $clientes->CorreoElectronico; ?>" required>

    <label class="form-label" for="fechaDeNacimiento">Fecha de nacimiento:</label>
    <input type="date" class="form-control" name="fechaDeNacimiento" value="<?php echo $clientes->FechaNacimiento; ?>" required></textarea>

    <label for="dni">Documento:</label>
    <input type="text" class="form-control" id="dni" name="dni" value="<?php echo $clientes->DNI; ?>" required>

    <label for="direccion">Direccion:</label>
    <input type="text" class="form-control" id="direccion" name="direccion" value="<?php echo $clientes->Direccion; ?>" required>

    <button class="btn btn-success" type="submit">Actualizar Cliente</button>
</form>