<?php require_once 'templates/Header.phtml'; ?>
<form action="AgregarCliente" method="post">

    <label for="nombre">Nombre:</label>
    <input type="text" class="form-control" id="nombre" name="nombre" required>

    <label class="form-label" for="apellido">Apellido:</label>
    <input type="text" class="form-control" id="apellido" name="apellido" required>


    <label for="correoElectronico">Correo Electronico:</label>
    <input type="email" class="form-control" id="correoElectronico" name="correoElectronico" required>

    <label class="form-label" for="fechaDeNacimiento">Fecha de nacimiento:</label>
    <input type="date" class="form-control" name="fechaDeNacimiento" required></textarea>

    <label for="dni">Documento:</label>
    <input type="text" class="form-control" id="dni" name="dni" step="0.01" required>

    <label for="direccion">Direccion:</label>
    <input type="text" class="form-control" id="direccion" name="direccion" step="0.01" required>

    <button class="btn btn-success" type="submit">Agregar Cliente</button>
</form>
<?php require_once 'templates/Footer.phtml'; ?>