    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <base href="<?php echo BASE_URL ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="css/estilos.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <title>Travel Around The World</title>
    </head>

    <header>
        <div class="barraNav">
            <h1>Travel Around The World</h1>
            <a href="<?php echo BASE_URL . 'Home'; ?>">Home</a>
            <a href="<?php echo BASE_URL . 'Clientes'; ?>">Clientes</a>
            <a href="<?php echo BASE_URL . 'Viajes'; ?>">Viajes</a>
            <?php if (!isset($_SESSION['id_usuario'])) : ?>
                <a class="nav-link" aria-current="page" href="<?php echo BASE_URL . 'LogIn'; ?>">Ingresar</a>
            <?php else : ?>
                <a class="nav-link" aria-current="page" href="<?php echo BASE_URL . 'LogOut'; ?>">Logout (<?= $_SESSION['nombreUsuario'] ?>)</a>
            <?php endif ?>
    </header>

    <body>