
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<body>
    <h2>Iniciar Sesión</h2>
    <form action="autorizacion" method="POST">
        <div>
            <label class="form-label" for="nombreUsuario">Nombre de Usuario:</label>
            <input type="text" name="nombreUsuario" id="nombreUsuario" class="form-control" required><br><br>
        </div>
        <div>
            <label class="form-label" for="password">Contraseña:</label>
            <input type="password" name="password" id="password" class="form-control" required><br><br>
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div>
        <?php endif ?>
        <button type="submit" class="btn btn-secondary mt-3">Iniciar Sesion</button>
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>
