<?php if (isset($_SESSION['id_usuario'])) { ?>
    <div class="d-grid gap-2 col-6 mx-auto">
        <a href="<?php echo BASE_URL . 'formAgregarViaje/'; ?>" class="btn btn-success btn-sm">Agregar Viaje</a>

    </div>
<?php } ?>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Nombre del Destino</th>
            <th>Ver Detalle</th>
            <?php if (isset($_SESSION['id_usuario'])) { ?>
                <th>Opciones</th>
            <?php } ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($viajes as $viaje) { ?>
            <tr>
                <td><?php echo $viaje->Destino; ?></td>
                <td><a href="<?php echo BASE_URL . 'viaje/' . $viaje->ID_Viaje; ?>" class="btn btn-primary btn-sm">Ver Detalle</a></td>

                <?php if (isset($_SESSION['id_usuario'])) { ?>
                    <td>
                        <a href="<?php echo BASE_URL . 'formActualizarViaje/' . $viaje->ID_Viaje; ?>" class="btn btn-warning">Editar</a>
                        <a href="<?php echo BASE_URL . 'eliminarViaje/' . $viaje->ID_Viaje; ?>" class="btn btn-danger">Eliminar</a>
                    </td>
                <?php } ?>

            </tr>
        <?php } ?>
    </tbody>
</table>