<h2>Viajes</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID Viaje</th>
            <th>Destino</th>
            <th>Fecha de Salida</th>
            <th>Fecha de Regreso</th>
            <th>Descripción</th>
            <th>Precio</th>
            <th>ID Cliente</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <?php if (isset($_SESSION['id_usuario'])) { ?>
                <th>Opciones</th>
            <?php } ?>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?php echo $viajes->ID_Viaje; ?></td>
            <td><?php echo $viajes->Destino; ?></td>
            <td><?php echo $viajes->FechaSalida; ?></td>
            <td><?php echo $viajes->FechaRegreso; ?></td>
            <td><?php echo $viajes->Descripcion; ?></td>
            <td><?php echo $viajes->Precio; ?></td>
            <td><?php echo $viajes->id_Cliente; ?></td>
            <td> <?php echo $cliente->Nombre; ?></td>
            <td> <?php echo $cliente->Apellido; ?></td>
            <?php if (isset($_SESSION['id_usuario'])) { ?>
                <td>
                    <a href="<?php echo BASE_URL . 'formActualizarViaje/' . $viajes->ID_Viaje; ?>" class="btn btn-warning">Editar</a>
                    <a href="<?php echo BASE_URL . 'eliminarViaje/' . $viajes->ID_Viaje; ?>" class="btn btn-danger">Eliminar</a>
                </td>
            <?php } ?>
        </tr>
    </tbody>
</table>