<?php require_once 'templates/Header.phtml'; ?>

<?php if ($isAdmin) { ?>
    <div class="d-grid gap-2 col-6 mx-auto">
        <?php if ($isAdmin) { ?>
            <a href="<?php echo BASE_URL . 'FormAgregarViaje/'; ?>" class="btn btn-success btn-sm">Agregar Viaje</a>
        <?php } ?>
    </div>
<?php } ?>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Nombre del Destino</th>
            <th>Ver Detalle</th>
            <?php if ($isAdmin) { ?>
                <th>Opciones</th>
            <?php } ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($viajes as $viaje) { ?>
            <tr>
                <td><?php echo $viaje->Destino; ?></td>
                <td><a href="<?php echo BASE_URL . 'ViajeDetalles/' . $viaje->ID_Viaje; ?>" class="btn btn-primary btn-sm">Ver Detalle</a></td>

                <?php if ($isAdmin) { ?>
                    <td>
                        <a href="<?php echo BASE_URL . 'FormActualizarViaje/' . $viaje->ID_Viaje; ?>" class="btn btn-warning">Editar</a>
                        <a href="<?php echo BASE_URL . 'EliminarViaje/' . $viaje->ID_Viaje; ?>" class="btn btn-danger">Eliminar</a>
                    </td>
                <?php } ?>

            </tr>
        <?php } ?>
    </tbody>
</table>
<?php require_once 'templates/Footer.phtml'; ?>