<?php require_once 'templates/Header.phtml'; ?>

<h2>Viajes</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID Viaje</th>
            <th>Destino</th>
            <th>Fecha de Salida</th>
            <th>Fecha de Regreso</th>
            <th>Descripción</th>
            <th>Precio</th>
            <th>ID Cliente</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <?php if ($isAdmin) { ?>
                <th>Opciones</th>
            <?php } ?>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?php echo $viajes->id_viaje; ?></td>
            <td><?php echo $viajes->destino; ?></td>
            <td><?php echo $viajes->fecha_salida; ?></td>
            <td><?php echo $viajes->fecha_regreso; ?></td>
            <td><?php echo $viajes->descripcion; ?></td>
            <td><?php echo $viajes->precio; ?></td>
            <td><?php echo $viajes->id_cliente; ?></td>
            <td> <?php echo $clientes->nombre; ?></td>
            <td> <?php echo $clientes->apellido; ?></td>
            <?php if ($isAdmin) { ?>
                <td>
                    <a href="<?php echo BASE_URL . 'FormActualizarViaje/' . $viajes->id_viaje; ?>" class="btn btn-warning">Editar</a>
                    <a href="<?php echo BASE_URL . 'EliminarViaje/' . $viajes->id_viaje; ?>" class="btn btn-danger">Eliminar</a>
                </td>
            <?php } ?>
        </tr>
    </tbody>
</table>

<?php require_once 'templates/Footer.phtml'; ?>