
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<table>
    <thead>
        <tr>
            <th>Nombre del Destino</th>
            <th>Ver Detalle</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($viajes as $viaje) { ?>
            <tr>
                <td><?php echo $viaje->Destino; ?></td>
                <td><a href="<?php echo BASE_URL . 'viaje/' . $viaje->ID_Viaje; ?>" class="btn btn-primary btn-sm">Ver Detalle</a></td>
            <td>  
            <a href="<?php echo BASE_URL . 'actualizarViaje/' . $viaje->ID_Viaje; ?>" class="btn btn-warning">Editar</a>
            <a href="<?php echo BASE_URL . 'eliminarViaje/' . $viaje->ID_Viaje; ?>" class="btn btn-danger">Eliminar</a>
        </td>
            </tr>
        <?php } ?>
    </tbody>
</table>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<?php require_once 'templates/footer.phtml'; ?>
